// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIKUzgNqw7taOZ-QUvTiefEEpp8k48RXE',
    appId: '1:703774297124:web:d933ec3ea07c8768da9cb1',
    messagingSenderId: '703774297124',
    projectId: 'restaurantes-055',
    authDomain: 'restaurantes-055.firebaseapp.com',
    storageBucket: 'restaurantes-055.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxkMtOfX0MRjZ_XKTC-h1BZo8pK8Rk8c',
    appId: '1:703774297124:android:51b44f64022e7962da9cb1',
    messagingSenderId: '703774297124',
    projectId: 'restaurantes-055',
    storageBucket: 'restaurantes-055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-6nBCeZV7ooH9gkIDW8fPFPbuInmrfs',
    appId: '1:703774297124:ios:f53d977156ebe253da9cb1',
    messagingSenderId: '703774297124',
    projectId: 'restaurantes-055',
    storageBucket: 'restaurantes-055.appspot.com',
    iosBundleId: 'com.example.helloWorldApp',
  );
}
